const THRESHOLD = { strip_basin: 0.65, strip_deck: 0.65, restore_glamour_vanity: 0.70 };
const C = { bg:'#101423', gold:'#f6c74a', gold2:'#fff0a0', cyan:'#66e6ff', panel:'rgba(7,16,22,.94)', dark:'#151b19', concrete:'#343936', algae:'#2e5b40', rust:'#8f3d20' };
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const lerp=(a,b,t)=>a+(b-a)*t;
const inRect=(p,r)=>p.x>=r.x&&p.x<=r.x+r.w&&p.y>=r.y&&p.y<=r.y+r.h;
const d2=(ax,ay,bx,by)=>{const x=ax-bx,y=ay-by;return x*x+y*y};
function rr(x,y,w,h,r=12){const p=new Path2D(),q=Math.min(r,w/2,h/2);p.moveTo(x+q,y);p.lineTo(x+w-q,y);p.quadraticCurveTo(x+w,y,x+w,y+q);p.lineTo(x+w,y+h-q);p.quadraticCurveTo(x+w,y+h,x+w-q,y+h);p.lineTo(x+q,y+h);p.quadraticCurveTo(x,y+h,x,y+h-q);p.lineTo(x,y+q);p.quadraticCurveTo(x,y,x+q,y);p.closePath();return p}
function rectTarget(r){return{bounds:r,path:rr(r.x,r.y,r.w,r.h,14),contains:(x,y)=>x>=r.x&&x<=r.x+r.w&&y>=r.y&&y<=r.y+r.h}}
function deckTarget(g){const o=g.outer,b=g.basin,k=14,rs=[{x:o.x,y:o.y,w:o.w,h:b.y-o.y-k},{x:o.x,y:b.y+b.h+k,w:o.w,h:o.y+o.h-(b.y+b.h+k)},{x:o.x,y:b.y-k,w:b.x-o.x-k,h:b.h+2*k},{x:b.x+b.w+k,y:b.y-k,w:o.x+o.w-(b.x+b.w+k),h:b.h+2*k}].filter(r=>r.w>0&&r.h>0),p=new Path2D();rs.forEach(r=>p.addPath(rr(r.x,r.y,r.w,r.h,7)));return{bounds:o,path:p,contains:(x,y)=>rs.some(r=>x>=r.x&&x<=r.x+r.w&&y>=r.y&&y<=r.y+r.h)}}
function grid(target,size=14){const cells=[],b=target.bounds;for(let y=b.y+size/2;y<b.y+b.h;y+=size)for(let x=b.x+size/2;x<b.x+b.w;x+=size)if(target.contains(x,y))cells.push({x,y,done:false});return{cells,done:0,total:Math.max(1,cells.length),size}}
function panel(title,text){const n=document.createElement('section');n.setAttribute('role','dialog');n.setAttribute('aria-modal','false');n.style.cssText='position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:min(560px,calc(100% - 48px));padding:20px;border:1px solid rgba(102,230,255,.55);border-radius:14px;background:rgba(7,16,22,.96);box-shadow:0 20px 70px #000a;color:#eef9ff;font-family:system-ui,sans-serif;pointer-events:auto;z-index:20';const h=document.createElement('h2');h.textContent=title;h.style.cssText='margin:0 0 8px;color:#66e6ff;font-size:21px';const p=document.createElement('p');p.textContent=text;p.style.cssText='margin:0 0 14px;color:#c8d6df;line-height:1.5';n.append(h,p);return{n,h,p}}
function button(text,color='#66e6ff'){const b=document.createElement('button');b.type='button';b.textContent=text;b.style.cssText=`border:1px solid ${color};border-radius:8px;background:#ffffff10;color:#fff;padding:10px 13px;font:700 13px system-ui;cursor:pointer`;return b}

export default function createGame({canvas,ctx,overlay,concept,scenario,getState,actions,audio,toCanvasPoint,debug}){
  if(!canvas||!ctx||!scenario)throw new Error('fake_it_till_you_clean_it requires canvas, ctx, scenario');
  canvas.style.touchAction='none';
  const W=canvas.width,H=canvas.height;
  const g={outer:{x:W*.105,y:H*.35,w:W*.79,h:H*.55},basin:{x:W*.19,y:H*.47,w:W*.62,h:H*.34},bag:{x:W*.79,y:H*.70,w:W*.14,h:H*.21},pump:{x:W*.045,y:H*.54,w:W*.10,h:H*.19},vanity:{x:W*.20,y:H*.17,w:W*.60,h:H*.59},safe:{x:W*.41,y:H*.28,w:W*.20,h:H*.30}};
  const substrate=document.createElement('canvas'),gold=document.createElement('canvas');substrate.width=gold.width=W;substrate.height=gold.height=H;const sub=substrate.getContext('2d'),top=gold.getContext('2d');
  const debris=[['ring',W*.22,H*.30,22],['cup',W*.42,H*.41,16],['foil',W*.61,H*.29,18],['leaves',W*.67,H*.56,20]].map(([id,x,y,r])=>({id,x,y,r,ox:x,oy:y,bagged:false}));
  const particles=[],off=[];let frame=0,destroyed=false,phase='',surfaceId=null,target=null,occ=null,surfaceSent=false,pointer=false,pid=null,last=null,drag=null,reportDrag=false,report=.5,pumpAt=0,pump=0,pumpSent=false,seamAt=0,seam=0,vanitySent=false,safeAt=0,safe=0,receiptSent=false,choiceOpen=false,lastNoise=0,reportUi=null;

  const overlayOld=overlay?{inset:overlay.style.inset,bottom:overlay.style.bottom,display:overlay.style.display,pointerEvents:overlay.style.pointerEvents}:null;
  if(overlay){overlay.style.inset='0';overlay.style.bottom='0';overlay.style.display='block';overlay.style.pointerEvents='none';const q=overlay.querySelector?.('#action-prompt');if(q)q.style.cssText+=';position:absolute;left:50%;bottom:20px;transform:translateX(-50%);white-space:nowrap;z-index:10'}

  const brief=panel('CONTRACT BRIEFING // ESTATE 04','Strip the camera-only luxury finish, document what it concealed, then follow the staging pattern into the connected glamour vanity.');brief.n.setAttribute('aria-label','Cleanup contract briefing');const briefBtn=button('ACKNOWLEDGE BRIEFING (E)');brief.n.append(briefBtn);overlay.append(brief.n);
  const choices=panel('EVIDENCE DISPOSITION','Choose one disposition for the shot list and hidden-safe receipts.');choices.n.hidden=true;choices.n.setAttribute('aria-label','Evidence disposition choices');const row=document.createElement('div');row.style.cssText='display:grid;grid-template-columns:repeat(3,1fr);gap:10px';(scenario.steps.find(s=>s.id==='disposition')?.options||[]).forEach(o=>{const b=button(o.label,o.id==='archive'?C.gold:C.cyan);b.setAttribute('aria-label',`${o.label}: ${o.consequence}`);b.onclick=e=>{e.stopPropagation();const r=actions.attemptStep('disposition',{option:o.id,source:'candidate_disposition_button'});if(r.ok){choiceOpen=false;choices.n.hidden=true;audio.tone({frequency:o.id==='archive'?720:520,duration:.15,gain:.04});ensureReport();debug.stateChanged('fake_it_disposition',{option:o.id})}};b.onkeydown=e=>{if(e.code==='Enter'||e.code==='Space')e.stopPropagation()};row.append(b)});choices.n.append(row);overlay.append(choices.n);
  function ensureReport(){if(reportUi)return reportUi;const p=panel('BEFORE / AFTER REPORT','Drag the divider to compare staged gold with the documented substrate. Press Enter to finalize.');p.n.style.top='auto';p.n.style.bottom='18px';p.n.style.transform='translateX(-50%)';const lab=document.createElement('label'),r=document.createElement('input');lab.style.cssText='display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:center;font:700 11px system-ui';r.type='range';r.min='0';r.max='100';r.value='50';r.setAttribute('aria-label','Before after comparison position');r.oninput=()=>{report=Number(r.value)/100;debug.stateChanged('fake_it_report_slider',{position:report})};lab.append('BEFORE',r,'AFTER');p.n.append(lab);overlay.append(p.n);reportUi={...p,r};return reportUi}

  const st=()=>getState(),pending=()=>st().pending_step?.id??null,done=id=>st().completedSteps?.includes(id)??false;
  function phaseOf(s){if(!s.startedAt||s.pending_step?.id==='inspect_objective')return'brief';const p=s.pending_step?.id;if(p==='collect_debris')return'debris';if(p==='drain_pool')return'drain';if(p==='strip_basin'||p==='strip_deck')return p;if(p==='reveal_decayed_surface')return'reveal';if(p==='restore_glamour_vanity')return'vanity';if(p==='safe_receipt_clue')return'safe';if(p==='disposition')return'choice';if(!p&&s.scenario&&s.completedSteps.length===s.scenario.steps.length)return s.finished?'report_done':'report';return'idle'}
  const coverage=()=>occ?occ.done/occ.total:0;

  function buildSurface(id){surfaceId=id;target=id==='strip_basin'?rectTarget(g.basin):id==='strip_deck'?deckTarget(g):rectTarget(g.vanity);occ=grid(target,id==='restore_glamour_vanity'?13:14);surfaceSent=false;vanitySent=false;seamAt=seam=0;sub.clearRect(0,0,W,H);top.clearRect(0,0,W,H);sub.save();sub.clip(target.path);if(id==='restore_glamour_vanity'){const q=sub.createLinearGradient(g.vanity.x,g.vanity.y,g.vanity.x+g.vanity.w,g.vanity.y+g.vanity.h);q.addColorStop(0,'#34383f');q.addColorStop(.6,'#171b20');q.addColorStop(1,'#3a2633');sub.fillStyle=q;sub.fillRect(g.vanity.x,g.vanity.y,g.vanity.w,g.vanity.h);sub.strokeStyle=C.cyan;sub.lineWidth=2;sub.strokeRect(g.safe.x,g.safe.y,g.safe.w,g.safe.h)}else{sub.fillStyle=id==='strip_basin'?C.dark:'#4a4741';sub.fillRect(target.bounds.x,target.bounds.y,target.bounds.w,target.bounds.h);sub.fillStyle=C.algae;for(let i=0;i<24;i++){sub.globalAlpha=.18+(i%4)*.04;sub.beginPath();sub.arc(target.bounds.x+((i*71)%Math.max(1,target.bounds.w)),target.bounds.y+((i*43)%Math.max(1,target.bounds.h)),10+(i%5)*5,0,Math.PI*2);sub.fill()}}sub.restore();top.save();top.clip(target.path);const q=top.createLinearGradient(target.bounds.x,target.bounds.y,target.bounds.x+target.bounds.w,target.bounds.y+target.bounds.h);if(id==='restore_glamour_vanity'){q.addColorStop(0,'#7b4e72');q.addColorStop(.45,'#f1d3e6');q.addColorStop(1,'#87537c')}else{q.addColorStop(0,'#9c6707');q.addColorStop(.3,C.gold);q.addColorStop(.48,C.gold2);q.addColorStop(1,'#7a4a00')}top.fillStyle=q;top.fillRect(target.bounds.x,target.bounds.y,target.bounds.w,target.bounds.h);for(let i=0;i<80;i++){top.fillStyle=i%4?'#ffd44355':'#ffffffaa';top.beginPath();top.arc(target.bounds.x+((i*59)%Math.max(1,target.bounds.w)),target.bounds.y+((i*37)%Math.max(1,target.bounds.h)),1+(i%3),0,Math.PI*2);top.fill()}top.restore();debug.stateChanged('fake_it_surface',{step_id:id,cells:occ.total})}
  function sync(){const n=phaseOf(st());if(n===phase)return;phase=n;brief.n.hidden=n!=='brief';if(n!=='choice'){choiceOpen=false;choices.n.hidden=true}if(n==='strip_basin'||n==='strip_deck'||n==='vanity'){const id=n==='vanity'?'restore_glamour_vanity':n;if(surfaceId!==id)buildSurface(id)}else{target=occ=null;surfaceId=null}if(n==='safe'){safeAt=safe=0;receiptSent=false}if(n==='report'||n==='report_done')ensureReport();debug.stateChanged('fake_it_phase',{phase:n})}

  function mark(x,y,r){if(!target||!occ||!target.contains(x,y))return 0;let n=0,R=r*r;for(const c of occ.cells)if(!c.done&&d2(c.x,c.y,x,y)<=R){c.done=true;occ.done++;n++}return n}
  function flakes(x,y,n=5){for(let i=0;i<n;i++)particles.push({x:x+(Math.random()-.5)*10,y:y+(Math.random()-.5)*10,vx:(Math.random()-.5)*4.5,vy:-2-Math.random()*3,r:Math.random()*6,a:.95,s:3+Math.random()*4})}
  function erase(x,y,r,fx=true){if(!target||!target.contains(x,y))return false;const n=mark(x,y,r);top.save();top.clip(target.path);top.globalCompositeOperation='destination-out';const q=top.createRadialGradient(x,y,r*.15,x,y,r);q.addColorStop(0,'#000');q.addColorStop(.78,'#000e');q.addColorStop(1,'#0000');top.fillStyle=q;top.beginPath();top.arc(x,y,r,0,Math.PI*2);top.fill();top.restore();if(n){if(fx)flakes(x,y,Math.min(8,3+Math.ceil(n/3)));const now=performance.now();if(fx&&now-lastNoise>85){audio.noise({duration:.055,gain:.025,filterFrequency:1450});lastNoise=now}debug.stateChanged('fake_it_cleaning',{step_id:surfaceId,coverage:coverage()})}return n>0}
  function stroke(a,b,r){const d=Math.hypot(b.x-a.x,b.y-a.y),N=Math.max(1,Math.ceil(d/Math.max(5,r*.32)));for(let i=0;i<=N;i++){const t=i/N;erase(lerp(a.x,b.x,t),lerp(a.y,b.y,t),r)}maybeFinishSurface()}
  function keyboardClean(){if(!occ)return;const left=occ.cells.filter(c=>!c.done),count=Math.ceil(occ.total*(surfaceId==='restore_glamour_vanity'?.25:.24));left.slice(0,count).forEach(c=>erase(c.x,c.y,occ.size*.76,false));audio.noise({duration:.08,gain:.03,filterFrequency:1250});flakes(target.bounds.x+target.bounds.w/2,target.bounds.y+target.bounds.h/2,12);maybeFinishSurface()}
  function maybeFinishSurface(){if(!surfaceId||!occ||coverage()<THRESHOLD[surfaceId])return;if(surfaceId==='restore_glamour_vanity'){if(!seamAt){seamAt=performance.now();audio.tone({frequency:410,type:'triangle',duration:.16,gain:.04});debug.stateChanged('fake_it_safe_seam',{coverage:coverage()})}return}if(surfaceSent)return;surfaceSent=true;const r=actions.attemptStep(surfaceId,{source:'candidate_surface_threshold',coverage:Number(coverage().toFixed(4))});if(!r.ok)surfaceSent=false;else audio.tone({frequency:620,duration:.13,gain:.04})}

  function acknowledge(){if(!st().startedAt)actions.startSession();const r=done('inspect_objective')?{ok:true,reason:'already_completed'}:actions.attemptStep('inspect_objective',{source:'candidate_briefing'});if(r.ok){brief.n.hidden=true;audio.tone({frequency:520,duration:.1,gain:.03})}return r}
  function bagNext(){const x=debris.find(d=>!d.bagged);if(!x)return;x.bagged=true;x.x=g.bag.x+g.bag.w/2;x.y=g.bag.y+g.bag.h*.55;audio.tone({frequency:350+debris.filter(d=>d.bagged).length*35,duration:.08,gain:.03});finishDebris()}
  function finishDebris(){if(debris.every(d=>d.bagged)&&!done('collect_debris'))actions.attemptStep('collect_debris',{source:'candidate_debris_bag',debris_count:debris.length})}
  function startPump(){if(pending()!=='drain_pool')return false;if(!pumpAt){pumpAt=performance.now();pump=0;audio.tone({frequency:92,type:'sawtooth',duration:.28,gain:.03});debug.stateChanged('fake_it_pump_started')}return true}
  function reveal(){const r=actions.attemptStep('reveal_decayed_surface',{source:'candidate_q_reveal'});if(r.ok&&r.reason!=='already_completed'){audio.tone({frequency:660,type:'triangle',duration:.25,gain:.04});debug.stateChanged('fake_it_reveal')}return r}
  function inspectSafe(){if(pending()!=='safe_receipt_clue')return actions.attemptStep('safe_receipt_clue',{source:'candidate_safe_probe'});if(!safeAt){safeAt=performance.now();safe=0;audio.tone({frequency:180,type:'square',duration:.12,gain:.025})}return{ok:true,reason:'safe_opening'}}
  function openChoice(){if(pending()!=='disposition')return actions.attemptStep('disposition',{source:'candidate_disposition_probe'});choiceOpen=true;choices.n.hidden=false;queueMicrotask(()=>choices.n.querySelector('button')?.focus());return{ok:true,reason:'choice_opened'}}

  function resetLocal(){debris.forEach(d=>{d.x=d.ox;d.y=d.oy;d.bagged=false});surfaceId=null;target=occ=null;surfaceSent=false;pumpAt=pump=0;pumpSent=false;seamAt=seam=0;vanitySent=false;safeAt=safe=0;receiptSent=false;choiceOpen=false;report=.5;drag=null;reportDrag=false;particles.length=0;choices.n.hidden=true;if(reportUi){reportUi.n.remove();reportUi=null}}

  function pool(time,before=false,after=false){const sky=ctx.createLinearGradient(0,0,0,H*.42);sky.addColorStop(0,C.bg);sky.addColorStop(1,'#302548');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle=before?'#8a7446':'#524b42';ctx.fillRect(0,H*.35,W,H*.65);ctx.fillStyle='#201d1a';ctx.fill(rr(g.outer.x-8,g.outer.y-8,g.outer.w+16,g.outer.h+16,24));ctx.fillStyle=before?'#d1aa34':'#68615a';ctx.fill(rr(g.outer.x,g.outer.y,g.outer.w,g.outer.h,20));const drained=done('drain_pool')||['strip_basin','strip_deck','reveal'].includes(phase)||done('reveal_decayed_surface'),wl=before?1:(pumpAt&&!done('drain_pool')?1-pump:(drained?0:1));if(wl>.005&&!after){const hh=g.basin.h*wl,y=g.basin.y+g.basin.h-hh,q=ctx.createLinearGradient(0,y,0,g.basin.y+g.basin.h);q.addColorStop(0,'#54e2ffd8');q.addColorStop(1,'#0d4c6bf4');ctx.fillStyle=q;ctx.fill(rr(g.basin.x,y,g.basin.w,hh,15));ctx.strokeStyle='#d0fbffaa';ctx.beginPath();const z=Math.sin(time*.004)*4;ctx.moveTo(g.basin.x+12,y+z);ctx.bezierCurveTo(g.basin.x+g.basin.w*.3,y-z,g.basin.x+g.basin.w*.7,y+z,g.basin.x+g.basin.w-12,y-z);ctx.stroke()}else{ctx.fillStyle=before?'#bd8e1e':C.concrete;ctx.fill(rr(g.basin.x,g.basin.y,g.basin.w,g.basin.h,15))}if(done('reveal_decayed_surface')||after)decay();if(phase==='debris')drawDebris();bag();pumpBox()}
  function decay(){const b=g.basin;ctx.fillStyle='#2e5b4066';for(let i=0;i<10;i++){ctx.beginPath();ctx.ellipse(b.x+35+((i*83)%(b.w-70)),b.y+20+((i*47)%(b.h-40)),18+(i%4)*7,10+(i%3)*5,i*.3,0,Math.PI*2);ctx.fill()}ctx.strokeStyle='#090c0b';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(b.x+45,b.y+22);ctx.lineTo(b.x+b.w*.33,b.y+b.h*.56);ctx.lineTo(b.x+b.w*.51,b.y+b.h*.44);ctx.lineTo(b.x+b.w-46,b.y+b.h*.77);ctx.stroke();ctx.strokeStyle=C.rust;ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(b.x+b.w*.46,b.y+b.h*.48);ctx.lineTo(b.x+b.w*.62,b.y+b.h*.48);ctx.moveTo(b.x+b.w*.53,b.y+b.h*.39);ctx.lineTo(b.x+b.w*.53,b.y+b.h*.61);ctx.stroke();ctx.fillStyle='#f2ecd8';ctx.fillRect(b.x+b.w-176,b.y+22,150,68);ctx.fillStyle='#172026';ctx.font='700 10px monospace';ctx.fillText('SHOT LIST // FRAME 04',b.x+b.w-166,b.y+40);ctx.fillStyle='#b53b2f';ctx.fillText('GOLD ONLY WHERE FRAME REACHES',b.x+b.w-166,b.y+60);ctx.fillStyle='#4c5559';ctx.fillText('NEXT: GLAMOUR VANITY',b.x+b.w-166,b.y+77)}
  function drawDebris(){debris.filter(d=>!d.bagged).forEach((d,i)=>{ctx.save();ctx.translate(d.x,d.y);ctx.fillStyle=i===1?'#e35d6a':i===2?C.gold2:'#dfe6e9';if(i===0){ctx.strokeStyle=ctx.fillStyle;ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,d.r,0,Math.PI*2);ctx.stroke()}else if(i===3){ctx.fillStyle='#6d8b4b';for(let j=0;j<5;j++){ctx.beginPath();ctx.ellipse((j-2)*7,(j%2)*6,8,4,j*.5,0,Math.PI*2);ctx.fill()}}else ctx.fillRect(-d.r*.7,-d.r*.5,d.r*1.4,d.r);ctx.restore()})}
  function bag(){ctx.fillStyle='#0d1418dd';ctx.fill(rr(g.bag.x,g.bag.y,g.bag.w,g.bag.h,10));ctx.strokeStyle=phase==='debris'?C.cyan:'#ffffff22';ctx.stroke(rr(g.bag.x,g.bag.y,g.bag.w,g.bag.h,10));ctx.fillStyle='#d7e8ef';ctx.font='700 10px monospace';ctx.textAlign='center';ctx.fillText('CLEANUP BAG',g.bag.x+g.bag.w/2,g.bag.y+24);ctx.fillText(`${debris.filter(d=>d.bagged).length}/4`,g.bag.x+g.bag.w/2,g.bag.y+44);ctx.textAlign='left'}
  function pumpBox(){ctx.fillStyle='#1d2830';ctx.fill(rr(g.pump.x,g.pump.y,g.pump.w,g.pump.h,10));ctx.strokeStyle=phase==='drain'?C.cyan:'#56646a';ctx.stroke(rr(g.pump.x,g.pump.y,g.pump.w,g.pump.h,10));ctx.fillStyle=pumpAt&&!done('drain_pool')?'#7cffb0':C.gold;ctx.beginPath();ctx.arc(g.pump.x+g.pump.w/2,g.pump.y+30,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d7e8ef';ctx.font='700 10px monospace';ctx.textAlign='center';ctx.fillText('PUMP',g.pump.x+g.pump.w/2,g.pump.y+g.pump.h-18);ctx.textAlign='left'}
  function surface(){ctx.drawImage(substrate,0,0);ctx.drawImage(gold,0,0);ctx.fillStyle=C.panel;ctx.fill(rr(24,24,220,56,9));ctx.fillStyle=C.cyan;ctx.font='800 17px monospace';ctx.fillText(`${Math.round(coverage()*100)}% CLEARED`,38,59)}
  function vanity(){const q=ctx.createLinearGradient(0,0,W,H);q.addColorStop(0,'#1d1422');q.addColorStop(1,'#362039');ctx.fillStyle=q;ctx.fillRect(0,0,W,H);const clean=done('restore_glamour_vanity')||phase==='safe'||phase==='choice';ctx.fillStyle='#16151a';ctx.fill(rr(g.vanity.x-28,g.vanity.y-28,g.vanity.w+56,g.vanity.h+95,22));ctx.fillStyle=clean?'#22272c':'#6c5269';ctx.fill(rr(g.vanity.x,g.vanity.y,g.vanity.w,g.vanity.h,18));for(let i=0;i<7;i++){const y=g.vanity.y+28+i*((g.vanity.h-56)/6);ctx.fillStyle='#ffdca8';ctx.beginPath();ctx.arc(g.vanity.x-13,y,7,0,Math.PI*2);ctx.arc(g.vanity.x+g.vanity.w+13,y,7,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#2a1c28';ctx.fillRect(g.vanity.x-38,g.vanity.y+g.vanity.h+8,g.vanity.w+76,58);if(phase==='vanity')surface();if(seamAt||done('restore_glamour_vanity')){ctx.save();ctx.globalAlpha=done('restore_glamour_vanity')?1:.25+seam*.75;ctx.strokeStyle=C.cyan;ctx.lineWidth=2+seam*3;ctx.shadowColor=C.cyan;ctx.shadowBlur=8+seam*18;ctx.strokeRect(g.safe.x,g.safe.y,g.safe.w,g.safe.h);ctx.restore()}if(safeAt||done('safe_receipt_clue'))safeDoor()}
  function safeDoor(){const p=done('safe_receipt_clue')?1:safe;ctx.fillStyle='#090d10';ctx.fillRect(g.safe.x,g.safe.y,g.safe.w,g.safe.h);ctx.save();ctx.translate(g.safe.x,g.safe.y);ctx.transform(1-p*.72,.08*p,0,1,-g.safe.w*.08*p,0);ctx.fillStyle='#2f3941';ctx.fillRect(0,0,g.safe.w,g.safe.h);ctx.strokeStyle='#6f7d85';ctx.lineWidth=5;ctx.strokeRect(0,0,g.safe.w,g.safe.h);ctx.restore();if(p>.35){ctx.globalAlpha=clamp((p-.35)/.65,0,1);ctx.fillStyle='#f3eddc';const x=g.safe.x+g.safe.w*.18,y=g.safe.y+g.safe.h*.23;ctx.fillRect(x,y,g.safe.w*.64,g.safe.h*.52);ctx.fillStyle='#172026';ctx.font='700 9px monospace';ctx.fillText('PROP RENTAL // RECURRING',x+8,y+18);ctx.fillStyle='#b43d30';ctx.fillText('48 HOUR SHOOT',x+8,y+38);ctx.fillText('OWNED INVENTORY: $0',x+8,y+55);ctx.globalAlpha=1}}
  function reportDraw(time,finished){pool(time,false,true);ctx.save();ctx.beginPath();ctx.rect(0,0,W*report,H);ctx.clip();pool(time,true,false);ctx.restore();const x=W*report;ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke();ctx.fillStyle=C.panel;ctx.fill(rr(x-32,H*.43,64,48,10));ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='800 16px monospace';ctx.fillText('↔',x,H*.43+30);ctx.textAlign='left';if(finished){ctx.fillStyle=C.panel;ctx.fill(rr(W*.18,H*.15,W*.64,86,14));ctx.strokeStyle=C.gold;ctx.stroke(rr(W*.18,H*.15,W*.64,86,14));ctx.textAlign='center';ctx.fillStyle=C.gold;ctx.font='800 12px monospace';ctx.fillText('NEXT-ZONE HOOK LOGGED',W/2,H*.15+25);ctx.fillStyle='#eef6f8';ctx.font='600 13px system-ui';ctx.fillText(scenario.next_hook?.label||'Third estate camera zone flagged',W/2,H*.15+52);ctx.textAlign='left'}}
  function flakesDraw(){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx;p.y+=p.vy;p.vy+=.15;p.r+=p.vr||0;p.a-=.026;if(p.a<=0){particles.splice(i,1);continue}ctx.save();ctx.globalAlpha=p.a;ctx.translate(p.x,p.y);ctx.rotate(p.r);ctx.fillStyle=p.a>.45?C.gold2:C.gold;ctx.fillRect(-p.s/2,-p.s/2,p.s,p.s*.55);ctx.restore()}}
  function prompt(){const q=overlay?.querySelector?.('#action-prompt');if(!q)return;const m={brief:'READ BRIEFING — E OR ACKNOWLEDGE',debris:'DRAG ALL DEBRIS INTO BAG',drain:pumpAt?'PUMP ACTIVE — WATERLINE DROPPING':'CLICK PUMP / E / SPACE',strip_basin:`SCRAPE BASIN — ${Math.round(coverage()*100)}%`,strip_deck:`SCRAPE DECK — ${Math.round(coverage()*100)}%`,reveal:'Q — DOCUMENT MOLD / CRACKS / REBAR / SHOT LIST',vanity:seamAt?'SAFE SEAM FOUND — EXPOSING LATCH':`CLEAN VANITY — ${Math.round(coverage()*100)}%`,safe:safeAt?'SAFE OPENING — READING RECEIPT':'E / CLICK SAFE — INSPECT RECEIPT',choice:choiceOpen?'CHOOSE PRESERVE / DISCARD / ARCHIVE':'F — OPEN DISPOSITION CHOICES',report:'DRAG BEFORE / AFTER DIVIDER — ENTER TO FINALIZE',report_done:'CONTRACT COMPLETE — NEXT ZONE FLAGGED'};q.textContent=m[phase]||'FOLLOW CONTRACT HUD'}
  function anim(t){if(pumpAt&&!pumpSent&&pending()==='drain_pool'){pump=clamp((t-pumpAt)/1800,0,1);if(pump>=1){pumpSent=true;const r=actions.attemptStep('drain_pool',{source:'candidate_pool_pump'});if(!r.ok)pumpSent=false}}if(seamAt&&pending()==='restore_glamour_vanity'){seam=clamp((t-seamAt)/780,0,1);if(seam>=1&&!vanitySent){vanitySent=true;const r=actions.attemptStep('restore_glamour_vanity',{source:'candidate_vanity_threshold',coverage:Number(coverage().toFixed(4)),safe_seam_exposed:true});if(!r.ok)vanitySent=false}}if(safeAt&&pending()==='safe_receipt_clue'){safe=clamp((t-safeAt)/900,0,1);if(safe>=1&&!receiptSent){receiptSent=true;const r=actions.attemptStep('safe_receipt_clue',{source:'candidate_safe_receipt',receipt_opened:true});if(!r.ok)receiptSent=false}}}
  function draw(t){if(destroyed)return;sync();anim(t);sync();ctx.clearRect(0,0,W,H);if(phase==='vanity'||phase==='safe'||phase==='choice')vanity();else if(phase==='report'||phase==='report_done')reportDraw(t,phase==='report_done');else{pool(t);if(phase==='strip_basin'||phase==='strip_deck')surface();if(phase==='reveal'){ctx.fillStyle=C.panel;ctx.fill(rr(W*.30,H*.08,W*.40,48,10));ctx.fillStyle=C.cyan;ctx.font='800 12px monospace';ctx.textAlign='center';ctx.fillText('SUBSTRATE EXPOSED // Q TO DOCUMENT DAMAGE',W/2,H*.08+29);ctx.textAlign='left'}}flakesDraw();prompt();frame=requestAnimationFrame(draw)}

  function pnt(e){return toCanvasPoint(e)}
  function down(e){const p=pnt(e);if(!p.inside)return;pid=e.pointerId;pointer=true;last=p;try{canvas.setPointerCapture(e.pointerId)}catch{}if(phase==='debris'){drag=debris.find(d=>!d.bagged&&d2(d.x,d.y,p.x,p.y)<=(d.r+10)**2)||null;return}if(phase==='drain'&&inRect(p,g.pump)){startPump();return}if(['strip_basin','strip_deck','vanity'].includes(phase)){erase(p.x,p.y,phase==='vanity'?27:30);maybeFinishSurface();return}if(phase==='safe'&&inRect(p,g.safe)){inspectSafe();return}if(phase==='report'||phase==='report_done')if(Math.abs(p.x-W*report)<=32)reportDrag=true}
  function move(e){if(!pointer||pid!==e.pointerId)return;const p=pnt(e);if(drag){drag.x=clamp(p.x,drag.r,W-drag.r);drag.y=clamp(p.y,drag.r,H-drag.r);last=p;return}if(reportDrag){report=clamp(p.x/W,.06,.94);if(reportUi)reportUi.r.value=String(Math.round(report*100));last=p;return}if(['strip_basin','strip_deck','vanity'].includes(phase))stroke(last,p,phase==='vanity'?27:30);last=p}
  function up(e){if(pid!==e.pointerId)return;const p=pnt(e);if(drag){if(inRect(p,g.bag)){drag.bagged=true;drag.x=g.bag.x+g.bag.w/2;drag.y=g.bag.y+g.bag.h*.55;audio.tone({frequency:360,duration:.08,gain:.03});finishDebris()}else{drag.x=drag.ox;drag.y=drag.oy}}drag=null;reportDrag=false;pointer=false;pid=null;last=null;try{if(canvas.hasPointerCapture?.(e.pointerId))canvas.releasePointerCapture(e.pointerId)}catch{}}
  canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);off.push(()=>canvas.removeEventListener('pointerdown',down),()=>canvas.removeEventListener('pointermove',move),()=>canvas.removeEventListener('pointerup',up),()=>canvas.removeEventListener('pointercancel',up));
  briefBtn.onclick=e=>{e.stopPropagation();acknowledge()};
  const host=e=>{if(e.detail?.reason==='profile_reset'){resetLocal();brief.n.hidden=false;phase=''}};window.addEventListener('scv:statechange',host);off.push(()=>window.removeEventListener('scv:statechange',host));
  frame=requestAnimationFrame(draw);

  return{
    handleVerb(verb){const s=st();if(verb==='reset_profile'){resetLocal();return{handled:true,result:actions.resetProfile()}}if(verb==='advance')return false;if(verb==='interact'){if(!s.startedAt||pending()==='inspect_objective')return{handled:true,result:acknowledge()};if(pending()==='drain_pool')return{handled:true,result:startPump()};if(pending()==='safe_receipt_clue')return{handled:true,result:inspectSafe()};return{handled:true,result:{ok:false,reason:'no_interaction_here',pending:pending()}}}if(verb==='inspect'){if(!s.startedAt)return false;if(!done('reveal_decayed_surface'))return{handled:true,result:reveal()};return{handled:true,result:{ok:false,reason:'reveal_already_logged'}}}if(verb==='commit_choice'){if(!s.startedAt)return false;if(!done('disposition'))return{handled:true,result:openChoice()};return false}if(verb==='core_action'){if(!s.startedAt)return false;const p=pending();if(p==='collect_debris'){bagNext();return{handled:true}}if(p==='drain_pool'){startPump();return{handled:true}}if(['strip_basin','strip_deck','restore_glamour_vanity'].includes(p)){if(surfaceId!==p)buildSurface(p);keyboardClean();return{handled:true}}return{handled:true,result:{ok:false,reason:'core_action_not_active',pending:p}}}return false},
    handlePlayerAction(){return false},
    destroy(){destroyed=true;cancelAnimationFrame(frame);off.splice(0).forEach(f=>{try{f()}catch{}});brief.n.remove();choices.n.remove();reportUi?.n.remove();if(overlay&&overlayOld){Object.assign(overlay.style,overlayOld)}},
    getDebugState(){return{phase,pending_step:pending(),debris_bagged:debris.filter(d=>d.bagged).map(d=>d.id),surface_step:surfaceId,coverage:Number(coverage().toFixed(4)),pump_progress:Number(pump.toFixed(4)),safe_seam_progress:Number(seam.toFixed(4)),safe_door_progress:Number(safe.toFixed(4)),disposition_open:choiceOpen,report_position:Number(report.toFixed(4)),next_hook_visible:phase==='report_done'}}
  }
}
